# Generated by Django 4.2.3 on 2023-07-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_employee_name_alter_employee_postion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='postion',
            new_name='position',
        ),
    ]
